name: coverage

on: pull_request

jobs:
  code_checks:
    name: Code Checks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14.x']

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@b173b6ec0100793626c2d9e6b90435061f4fc3e5
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm i -g lerna
        id: lerna

      - run: yarn install
        id: install

      - run: yarn run build
        id: turbo

      - uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        id: tests
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: yarn
          test-script: yarn run test:ci
