name: coverage

on: pull_request

jobs:
  code_checks:
    name: Code Checks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@aec1e95348a6983270197ef14011414346269b77
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/cache@v2
        name: Cache node_modules
        id: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/package.json') }}

      - uses: actions/cache@v2
        name: Cache Jest cache
        id: cache-jest-cache
        with:
          path: '.jest-cache'
          key: ${{ runner.os }}--jest-integration

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm i -g lerna
        id: lerna

      - run: yarn install
        id: install
        
      - run: yarn run build
        id: turbo

      - uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            package-manager: yarn

      - name: Tests
        run: npx jest -u
